import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-backgroundBg bg-swirl lg:bg-cover bg-top">
        {children}
      </body>
    </html>
  );
}
